# Desarrollo con hot-reload
FROM node:22-alpine
WORKDIR /app

# Instala deps primero para cachear
COPY package*.json ./
RUN npm ci

# Copiamos el resto (en runtime montaremos el volumen igualmente)
COPY . .

ENV HOST=0.0.0.0
EXPOSE 5173
CMD ["npm","run","dev","--","--host","0.0.0.0","--port","5173"]